.\"-
.\" 版權所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年11月4日
.Dt MGASK 1
.Os
.Sh 名稱
.Nm mgask
.Nd 向MobileGestalt問問題
.Sh 語法
.Nm
.Op Fl jpq
.Op Fl -gssc
.Op Fl -pretty
.Ar 問題…
.Sh 描述
這個
.Nm
工具程式會向MobileGestalt查詢指定問題的答案。
所有的陣列或字典會以JSON格式印出。
.Sh 選項
.Bl -tag -width indent
.It Fl c , -calculate
對於每個指明的鍵值，計算混淆後的鍵值。
這不會回傳鍵值的數值，而只會回傳混淆後的鍵值。
.It Fl -gssc
令
.Nm
的行為和舊式的
.Nm gssc
一樣。
.It Fl j , -json
把所有鍵值以JSON格式印出
.It Fl p , -plist
以NeXTSTEP plist格式印出所有鍵值。
.It Fl -pretty
印出經格式化的JSON。
視乎是否有指定
.Fl j
這只會影響陣列和字典，或整個輸出。
.It Fl q , -quiet
找不到鍵值時，不印出錯誤。
.El
.Sh 歷史
這個
.Nm
工具程式首先在2021年11月4日uikittools-ng在出現，由
.An Cameron Katri
編寫。
