.\"-
.\" 版權所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年10月18日
.Dt UISAVE 1
.Os
.Sh 名稱
.Nm uisave
.Nd 把影像和影片儲存到相機膠卷中
.Sh 語法
.Nm
.Ar 檔案......
.Sh 描述
把單個或更多個的影像和影片儲存到相機膠卷中。
不會移除元數據。
能夠儲存的影像和影片格式受iOS版本而異。
.Sh 另見
.Xr uishoot 1
.Sh 歷史
這個
.Nm
工具程式首先在2021年10月18日在uikittools-ng中出現，由
.An absidue
編寫。
