.\"-
.\" 版權所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年10月18日
.Dt UISHOOT 1
.Os
.Sh 名稱
.Nm uishoot
.Nd 截取螢幕截圖
.Sh 語法
.Nm
.Op Fl cp
.Op Fl d Ar 數字
.Op Fl f Op Ar jpeg | png | heic
.Op Fl o Ar 檔案
.Sh 描述
這個
.Nm
工具程式會截取一張螢幕截圖。
.Sh 選項
.Bl -tag -width indent
.It Fl c , -clipboard
把螢幕截圖儲存到剪貼板中。
.It Fl d , -delay Ar 數字
在截取螢幕截圖前，等待
.Ar 數字
秒的時間。
.It Fl p , -photos
把螢幕截圖加到相機膠卷中。
.It Fl f , -format Op Ar jpeg | png | heic
輸出並以指定的格式儲存螢幕截圖。
.It Fl o , -output Ar 檔案
把螢幕截圖儲存到
.Ar 檔案 。
如果
.Fl f
沒有設定那麼格式將會以
.Ar 檔案
的副檔名來推斷出來。
.El
.Sh 歷史
這個
.Nm
工具程式首先在2008年8月29日出現，由
.An Jay Qo Saurik Qc Freeman 編寫。
之後，
.An sunchipnacho
在2021年10月18日為uikitoools-ng重新實現了這一工具程式，並加入更多的選項。
