.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt LDRESTART 1
.Os
.Sh NAME
.Nm ldrestart
.Nd restarts currently running services
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will cause all launchd daemons to be restarted when invoked.
.Sh SEE ALSO
.Xr sbreload 1
.Sh HISTORY
The
.Nm
utility first appeared in uikittools on June 22, 2016, written by
.An Jay Qo Saurik Qc Freeman .
Later, it was reimplemented by
.An CoolStar
for the Chimera jailbreak on April 30, 2019.
