.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd November 6, 2021
.Dt MGASK 1
.Os
.Sh NAME
.Nm mgask
.Nd ask MobileGestalt questions
.Sh SYNOPSIS
.Nm
.Op Fl cjpq
.Op Fl -gssc
.Op Fl -pretty
.Ar question ...
.Sh DESCRIPTION
The
.Nm
utility will query MobileGestalt for the answer to the specified questions.
Any arrays or dictionaries will be printed in JSON.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl c , -calculate
For each key specified, calculate and print the obfuscated key.
This will not return the value of the key, only the obfuscated key.
.It Fl -gssc
Make
.Nm
act like the legacy
.Nm gssc .
.It Fl j , -json
Print all keys in JSON.
.It Fl p , -plist
Print all keys in NeXTSTEP plist format.
.It Fl -pretty
Pretty-print the JSON output.
This will apply to just array and dictionaries or the whole output if
.Fl j
is specified.
.It Fl q , -quiet
Don't print errors when a key is not found.
.El
.Sh HISTORY
The
.Nm
utility first appeared in uikittools on November 4, 2021, written by
.An Cameron Katri .
