.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt SBDIDLAUNCH 1
.Os
.Sh NAME
.Nm sbdidlaunch
.Nd waits until SpringBoard launches
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will wait until SpringBoard launches, then return 0.
.Sh SEE ALSO
.Xr sbreload 1
.Sh HISTORY
The
.Nm
utility first appeared in uikittools on June 20, 2010, written by
.An Jay Qo Saurik Qc Freeman .
Later, it was reimplemented by
.An CoolStar
for the Chimera jailbreak on April 30, 2019.
