.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd October 18, 2021
.Dt UISAVE 1
.Os
.Sh NAME
.Nm uisave
.Nd Save images and videos to the camera roll
.Sh SYNOPSIS
.Nm
.Ar
.Sh DESCRIPTION
Saves one or more images and videos to the camera roll.
Metadata does not get stripped.
Image and video formats that can be saved vary between iOS versions.
.Sh SEE ALSO
.Xr uishoot 1
.Sh HISTORY
The
.Nm
utility first appeared in uikittools-ng on October 18, 2021, written by
.An absidue .
