.\"-
.\" 版权所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年10月18日
.Dt UISAVE 1
.Os
.Sh 名称
.Nm uisave
.Nd 把图像与视频储存到相机胶卷中
.Sh 语法
.Nm
.Ar
.Sh 描述
把单个或多个的图像与视频储存到相机胶卷中。
不会移除元数据。
能够储存的图片与视频格式因iOS版本而异。
.Sh 另见
.Xr uishoot 1
.Sh 历史
.Nm
工具首先在2021年10月18日于uikittools-ng中出现，由
.An absidue
编写。
