.\"-
.\" 版权所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年10月18日
.Dt UISHOOT 1
.Os
.Sh 名称
.Nm uishoot
.Nd 屏幕截图
.Sh 语法
.Nm
.Op Fl cp
.Op Fl d Ar 数字
.Op Fl f Op Ar jpeg | png | heic
.Op Fl o Ar 文件
.Sh 描述
.Nm
工具会截取一张屏幕截图。
.Sh 选项
.Bl -tag -width indent
.It Fl c , -clipboard
将屏幕截图储存到剪贴板中。
.It Fl d , -delay Ar 数字
在截取屏幕截图前，等待
.Ar 数字
秒的时间。
.It Fl p , -photos
将屏幕截图添加到相机胶卷中。
.It Fl f , -format Op Ar jpeg | png | heic
输出并以指定的格式储存屏幕截图。
.It Fl o , -output Ar 档案
把屏幕截图储存到
.Ar 文件 。
如果
.Fl f
没有指定，那么最终格式将会以
.Ar 文件
的扩展名来推断出来。
.El
.Sh 历史
.Nm
工具首先在2008年8月29日出现，由
.An Jay Qo Saurik Qc Freeman 编写。
之后，
.An sunchipnacho
在2021年10月18日为uikitoools-ng重新实现了这一工具，并加入更多的选项。
