.\"-
.\" 版權所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年10月15日
.Dt UIALERT 1
.Os
.Sh 名稱
.Nm uialert
.Nd 顯示一個對話框。
.Sh 語法
.Nm
.Op Fl b Ar 正文
.Op Fl i Ar 提詞
.Op Fl j
.Op Fl p Ar primary
.Op Fl -priority Ar 數字
.Op Fl s Ar second
.Op Fl -secure Ar 提詞
.Op Fl t Ar third
.Op Fl -timeout Ar 數字
.Ar title
.Sh 描述
從命令列介面中來令在圖形介面中顯示一個原生對話框。
標題會被設定為
.Ar title
。
它會印出輸入的文字和被選擇的按鈕的索引到
.Ar 標準輸出
。
.Ss 輸出
.Bl -tag -width 4n -offset indent -compact
.It Sy 0
第一個按鈕被按下。
.It Sy 1
第二個按鈕被按下
.It Sy 2
第三個按鈕被按下。
.It Sy 3
對話框超時或在沒有回應的情況下被關閉。
.El
.Sh OPTIONS
.Bl -tag -width indent
.It Fl b , -body Ar 正文
把對話框的正文設定為
.Ar 正文 .
.It Fl i , -input Ar 提詞
加了一個提詞為
.Ar 提詞
的文字輸入區。
可以通過重複使用這個選項來加入多個輸入區。
.It Fl j , -json
以JSON格式印出輸出。
.It Fl p , -primary Ar 第一
把預設按鈕的文字設定為
.Ar 第一
。
而不是預設文字
.Qq 好
。
.It Fl -priority Ar 數字
把對話框的優先度設定為
.Ar 數字 .
.Ar 數字
一定要在0和3之間，且包含0和3。
如果不指名的話，那麼優先度就是1。.
這只會影響在
.Os macOS
上對話框的樣貌。
.It Fl s , -secondary Ar 第二
把第二個按鈕的文字設定為
.Ar 第二
，
如沒有設定，這按鈕將不會顯示。
.It Fl -secure Ar 提詞
這和
.Fl i
一樣，不過輸入的文字會當作密碼處理。
.It Fl t , -tertiary Ar 第三
把第三個按鈕的文字設定為
.Ar 第三 ,
如沒有設定，這按鈕將不會顯示。
.It Fl -timeout Ar 數字
在經過
.Ar 數字
秒後，關閉這個對話框。
.El
.Sh 例子
顯示一個第一個按鈕的文字為
.Qq 好
的對話框。
.Dl "uialert -b \*q這是正文\*q \*q有趣的標題\*q"
.Pp
顯示一個有兩個按鈕的對話框，而第一個按鈕的文字為
.Qq 取消
。
.Dl "uialert -p \*q取消\*q -s \*q仍要繼續\*q -b \*q繼續？\*q \*q這個操作將會刪除數據。\*q"
.Sh 歷史
這個
.Nm
工具程式首先在2008年2月26日出現在uikittools中，由
.An Jay Qo Saurik Qc Freeman
編寫。
之後
.An Cameron Katri
在2021年10月15日為uikittools-ng重新實現了這個工具程式，且用法完全不同。
