.\"-
.\" 版权所有 (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd 2021年8月23日
.Dt DEVICEINFO 1
.Os
.Sh 名称
.Nm deviceinfo
.Nd 输出设备信息
.Sh 语法
.Bl -compact -tag
.It
.Sy deviceinfo
cfversion
.It
.Sy deviceinfo
ecid
.Op Fl dh
.It
.Sy deviceinfo
locale
.Op Fl ilcvh
.It
.Sy deviceinfo
serial
.It
.Sy deviceinfo
uniqueid
.El
.Sh 描述
.Nm
输出指定的设备信息，然后退出。
.Sh 子命令
.Bl -tag -width indent
.It Ar cfversion
输出设备CoreFoundation版本.
.It Ar ecid Op Fl dh
输出设备的专有芯片ID (ECID)。
.Bl -tag -width indent
.It Fl d
以十进制输出ECID
.It Fl h
以十六进制输出ECID
未指定选项时，这是默认选项。
.El
.It Ar locale Op Fl ilcvh
以指定的格式输出系统区域设置。
以下的选项是可用的：
.Bl -tag -width indent
.It Fl i , -identifier
输出区域设置标识符，这是默认选项。
.It Fl l , -language
输出区域设置的语言代码。
.It Fl c , -country
输出区域设置的国家与地区代码。
.It Fl v , -variant
输出区域设置变种。
.It Fl h , -help
输出帮助。
.El
.It Ar serial
输出设备的序列号。
.It Ar uniqueid
输出设备的唯一标识符 (UDID)。
.El
.Sh 历史
.Nm
工具在2021年8月23日由
.An sunchipnacho
编写，取代uikittools-ng中的
.Nm cfversion，
.Nm ecidecid，
和
.Nm uiduid。
