.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd October 27, 2021
.Dt LSREBUILD 1
.Os
.Sh NAME
.Nm lsrebuild
.Nd rebuild LaunchServices.csstore cache
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will rebuild the cache used by LaunchServices.
.Sh HISTORY
The
.Nm
utility first appeared in uikittools-ng on October 27 2021, written by
.An Daniel Levi .
