.\"-
.\" Copyright (c) 2020-2021 ProcursusTeam
.\" SPDX-License-Identifier: BSD-4-Clause
.\"
.Dd August 19, 2021
.Dt SBRELOAD 1
.Os
.Sh NAME
.Nm sbreload
.Nd quickly reload SpringBoard
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
will restart the SpringBoard when invoked, and is much faster than alternatives such as
.Xr uicache 1 Fl r .
.Sh SEE ALSO
.Xr uicache 1
.Sh HISTORY
The
.Nm
utility first appeared in uikittools on December 3, 2010, written by
.An Jay Qo Saurik Qc Freeman .
Later, it was reimplemented by
.An CoolStar
for the Chimera jailbreak on April 30, 2019.
